version: 2
jobs:
  hoge:
    working_directory: ~/workspace
    docker:
      - image: node:9.4.0
    steps:
      - checkout
      - run:
          name: Echo
          command: echo hello, world.
workflows:
  version: 2
  fuga:
    jobs:
      - hoge
