---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: "./README.md"
  label: README.md
  match: "**/*"
- type: directory
  path: "./addition"
  label: addition
  create: all
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: contents
  label: contents
  create: all
  match: "**/*"
  new_doc_ext: md
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: ".vuepress/dist"
  install_dependencies_command: yarn install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn dev
